"""
WebAgentBridge — Pure‑Python bridge wrapping the Agent class for WebSocket
frontends.  No Qt / PyQt dependencies.

Architecture
────────────
A single bridge instance manages one agent session.  The lifecycle is:

    bridge.start(query, config_dict)
        → creates Agent in a daemon thread
        → runs process_query() → yields events
        → calls event_callback(event_dict) for each event

    bridge.pause()   / bridge.resume()   / bridge.stop()
        → thread‑safe control signals (events + threading.Event)

    bridge.get_conversation()
        → returns current message list

The event_callback is the glue to the outside world (FastAPI WebSocket,
CLI, or any consumer).  It receives raw dicts from the Agent's process_query
generator, plus synthetic events injected by the bridge itself.

Mapping: Agent events → frontend events
────────────────────────────────────────
The bridge translates raw agent events into the simplified event protocol
that the React frontend expects (see frontend/src/App.jsx):

    Agent → process_query yields:    Frontend receives:
    ──────────────────────────────────────────────────
    execution_state_change          → state_changed
    token_update                   → tokens_updated + context_updated
    user_query / turn / tool_call
      / tool_result / final        → conversation_changed
    (synthetic bridge events)      → status_message
"""

from __future__ import annotations

import threading
import queue
import traceback
from typing import Any, Callable, Dict, List, Optional

from agent import Agent
from agent.config import AgentConfig
from agent.controller import AgentController


# ══════════════════════════════════════════════════════════════════════════════
#  Bridge class
# ══════════════════════════════════════════════════════════════════════════════

class WebAgentBridge:
    """
    Thread‑safe bridge that runs one Agent session and emits events through
    a callback.  Designed to be driven by a FastAPI WebSocket endpoint.
    """

    def __init__(self, event_callback: Optional[Callable[[Dict[str, Any]], None]] = None):
        self._agent: Optional[Agent] = None
        self._thread: Optional[threading.Thread] = None
        self._running = False
        self._processing = False

        # Event primitives
        self._stop_event = threading.Event()
        self._pause_event = threading.Event()
        self._pause_event.set()          # start in "running" (not paused)

        # Query queue — the agent thread pulls from this
        self._query_queue: queue.Queue = queue.Queue()

        # Mailbox for config updates
        self._pending_config: Optional[AgentConfig] = None

        # Callback — called from the agent thread for every event
        self._event_callback = event_callback

        # Accumulated conversation history for frontend protocol
        self.history: List[Dict[str, Any]] = []

        # Track last assistant content to deduplicate turn vs final
        self._last_assistant_content: Optional[str] = None

        # Current config (for get_config / get_conversation)
        self._config: Optional[AgentConfig] = None
        self._session_id: Optional[str] = None

        # Controller integration (optional — used when Web UI wants to
        # reuse the existing AgentController instead of creating an Agent directly)
        self._controller: Optional[AgentController] = None

    # ── Public API ──────────────────────────────────────────────────────────

    @property
    def is_running(self) -> bool:
        return self._running and (self._thread is not None and self._thread.is_alive())

    @property
    def is_paused(self) -> bool:
        return not self._pause_event.is_set()

    @property
    def is_processing(self) -> bool:
        return self._processing

    # ── Event callback ──────────────────────────────────────────────────────

    def set_event_callback(self, callback: Callable[[Dict[str, Any]], None]) -> None:
        """
        Set or replace the event callback.  The callback will be called from
        the agent thread for every event generated by process_query().
        """
        self._event_callback = callback

    def set_controller(self, controller: AgentController) -> None:
        """
        Attach an existing AgentController instance.
        When set, bridge delegates start/pause/resume/stop to the controller
        and receives events via controller.set_event_callback().
        """
        self._controller = controller
        controller.set_event_callback(self._on_controller_event)

    # ── Lifecycle ───────────────────────────────────────────────────────────

    def start(self, query: str, config_dict: Optional[Dict[str, Any]] = None,
              preset_name: Optional[str] = None) -> None:
        """
        Start a new agent session.

        Args:
            query: Initial user query string.
            config_dict: Configuration dictionary (see AgentConfig fields).
            preset_name: Named preset to load instead of config_dict.
                         If both are given, config_dict values override the preset.
        """
        if self._controller is not None:
            # ── Delegate to controller ──────────────────────────────────
            if preset_name:
                self._running = True
                self._session_id = None
                overrides = config_dict or {}
                self._controller.start(query, preset_name=preset_name, **overrides)
                self._config = self._controller.get_config()
            else:
                config = AgentConfig(**config_dict)
                self._config = config
                self._running = True
                self._session_id = None
                self._controller.start(query, config)
            return

        if self.is_running:
            raise RuntimeError("Bridge is already running. Stop it first.")

        # Reset primitives
        self._stop_event.clear()
        self._pause_event.set()
        self._running = True
        self._processing = False

        # Build AgentConfig from the dict
        config = AgentConfig(**config_dict)
        self._config = config

        # Create agent (no Qt dependency, pure Python)
        self._agent = Agent(config)
        self._session_id = getattr(self._agent, 'session_id', None)

        # Queue the initial query
        self._query_queue.put(query)

        # Start background thread
        self._thread = threading.Thread(
            target=self._run_loop,
            daemon=True,
            name="web-bridge-agent",
        )
        self._thread.start()

    def continue_session(self, query: str) -> None:
        """
        Submit a follow‑up query to a running (or paused) agent.
        """
        if self._controller is not None:
            self._controller.continue_session(query)
            return
        if not self.is_running:
            raise RuntimeError("Bridge is not running. Start it first.")
        self.resume()
        self._query_queue.put(query)

    def pause(self) -> None:
        """Request the agent to pause after the current turn."""
        if self._controller is not None:
            self._controller.pause()
            return
        if not self.is_running:
            return
        self._pause_event.clear()
        if self._agent is not None:
            self._agent.request_pause()

    def resume(self) -> None:
        """Resume a paused agent."""
        if self._controller is not None:
            self._controller.resume()
            return
        self._pause_event.set()
        if self._agent is not None:
            self._agent._pause_requested = False

    def stop(self) -> None:
        """Request the agent to stop (finishes current operation then exits)."""
        if self._controller is not None:
            self._controller.stop()
            return
        self._stop_event.set()
        self._pause_event.set()  # unblock if paused

    # ── Query API ───────────────────────────────────────────────────────────

    def get_conversation(self) -> Optional[List[Dict[str, Any]]]:
        """Return the current conversation from the agent, if available."""
        if self._controller is not None:
            return self._controller.get_conversation()
        if self._agent is not None:
            return self._agent.conversation.copy()
        return None

    def get_config(self) -> Optional[AgentConfig]:
        if self._controller is not None:
            return self._controller.get_config()
        return self._config

    # ── Internal: event emission ────────────────────────────────────────────

    def _emit(self, event: Dict[str, Any]) -> None:
        """Thread‑safe event emission via callback."""
        print(f"📤 Sending to frontend: {event}")
        if self._event_callback is not None:
            try:
                self._event_callback(event)
            except Exception:
                traceback.print_exc()

    def _on_controller_event(self, event: Dict[str, Any]) -> None:
        """
        Callback registered with the controller via set_event_callback().
        Receives raw events from the controller's agent thread and maps
        them to the frontend protocol, exactly like _map_and_emit does
        for the standalone agent loop.
        """
        print(f"🔹 Bridge received event: {event.get('type')} — {str(event)[:200]}")
        self._map_and_emit(event)

    def _event_to_message(self, event: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Convert a process_query event into a frontend message dict.
        Raw events from process_query() have no 'role' key and use
        type-specific fields for content (e.g. 'result' for tool_result,
        'arguments' for tool_call).
        Returns None if the event doesn't map to a message.
        """
        event_type = event.get("type", "")

        if event_type == "turn":
            content = event.get("content", "")
            self._last_assistant_content = content
            msg = {
                "role": "assistant",
                "content": content,
            }
            print(f"✅ Converted {event_type} to message: {msg}")
            return msg

        elif event_type == "final":
            content = event.get("content", "")
            if content == self._last_assistant_content:
                print(f"⏭️ Skipping final — content matches last turn")
                return None
            msg = {
                "role": "assistant",
                "content": content,
            }
            print(f"✅ Converted {event_type} to message: {msg}")
            return msg

        elif event_type == "user_query":
            msg = {
                "role": "user",
                "content": event.get("content", ""),
            }
            print(f"✅ Converted {event_type} to message: {msg}")
            return msg

        elif event_type == "tool_call":
            tool_name = event.get("tool_name", "?")
            args = event.get("arguments", "")
            msg = {
                "role": "assistant",
                "content": f"[Tool call: {tool_name}({args})]",
            }
            print(f"✅ Converted {event_type} to message: {msg}")
            return msg

        elif event_type == "tool_result":
            msg = {
                "role": "tool",
                "content": event.get("result", ""),
            }
            print(f"✅ Converted {event_type} to message: {msg}")
            return msg

        return None

    def _translate_event(self, raw_event: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Translate a raw agent event into frontend protocol events.
        Returns a list of event dicts to send to the frontend.
        Does NOT forward the raw event — only high-level protocol events.
        """
        results: List[Dict[str, Any]] = []
        event_type = raw_event.get("type", "")

        if event_type == "execution_state_change":
            new_state = raw_event.get("new_state", "")
            frontend_state = self._map_agent_state(new_state)
            results.append({
                "type": "state_changed",
                "state": frontend_state,
                "is_running": self._get_is_running(),
            })

        elif event_type == "token_update":
            tokens_in = raw_event.get("total_input", 0)
            tokens_out = raw_event.get("total_output", 0)
            results.append({
                "type": "tokens_updated",
                "input": tokens_in,
                "output": tokens_out,
            })
            ctx = raw_event.get("context_length", 0)
            if ctx:
                results.append({
                    "type": "context_updated",
                    "context_length": ctx,
                })

        elif event_type in ("user_query", "turn", "tool_call", "tool_result", "final"):
            msg = self._event_to_message(raw_event)
            if msg is not None:
                self.history.append(msg)
            # Send full conversation snapshot
            results.append({
                "type": "conversation_changed",
                "messages": list(self.history),
            })
            if event_type == "final":
                results.append({
                    "type": "state_changed",
                    "state": "IDLE",
                    "is_running": self._get_is_running(),
                })

        elif event_type == "user_interaction_requested":
            results.append({
                "type": "state_changed",
                "state": "WAITING_FOR_USER",
                "is_running": self._get_is_running(),
            })

        elif event_type == "error":
            results.append({
                "type": "status_message",
                "text": f"⚠ Error: {raw_event.get('message', 'unknown')}",
            })

        # ── Synthetic bridge event: don't forward to frontend ────────────
        if event_type == "session_stop":
            return []

        # Stop handling
        if raw_event.get("stop_reason"):
            results.append({
                "type": "state_changed",
                "state": "IDLE",
                "is_running": self._get_is_running(),
            })

        return results

    def _map_and_emit(self, raw_event: Dict[str, Any]) -> None:
        """
        Map a raw agent event to frontend protocol events and emit each.
        Uses _translate_event to do the conversion.
        """
        for frontend_event in self._translate_event(raw_event):
            self._emit(frontend_event)

    # ── Internal: helpers ───────────────────────────────────────────────────

    def _get_is_running(self) -> bool:
        """
        Determine whether the agent/controller is still alive and can accept
        follow-up queries.  Works in both standalone and controller modes.
        """
        if self._controller is not None:
            # Controller mode — check controller's is_running if available
            if hasattr(self._controller, 'is_running'):
                return bool(self._controller.is_running)
            return True  # assume alive if we can't check
        # Standalone mode — check _running + thread alive
        return self._running and (self._thread is not None and self._thread.is_alive())

    @staticmethod
    def _map_agent_state(agent_state: str) -> str:
        """Map Agent/Controller state strings to frontend status values."""
        mapping = {
            "running": "RUNNING",
            "pausing": "PAUSED",
            "paused": "PAUSED",
            "idle": "IDLE",
            "error": "IDLE",
            "stopped": "IDLE",
            "completed": "IDLE",
            "ready": "IDLE",
            "waiting": "WAITING_FOR_USER",
        }
        return mapping.get(agent_state.lower(), agent_state.upper())

    @staticmethod
    def _map_role(msg: Dict[str, Any]) -> str:
        """Map internal message role to frontend role."""
        role = msg.get("role", "system")
        mapping = {
            "user": "user",
            "assistant": "assistant",
            "system": "system",
            "tool": "tool_result",
        }
        return mapping.get(role, role)

    @staticmethod
    def _map_content(msg: Dict[str, Any]) -> str:
        """Extract display content from a message dict."""
        content = msg.get("content", "")
        if isinstance(content, list):
            # Multi‑part content — concatenate text parts
            texts = []
            for part in content:
                if isinstance(part, dict):
                    if part.get("type") == "text":
                        texts.append(part.get("text", ""))
                    elif part.get("type") == "tool_use":
                        texts.append(f"[Tool: {part.get('name', '?')}]")
                elif isinstance(part, str):
                    texts.append(part)
            return "\n".join(texts)
        if not isinstance(content, str):
            return str(content)
        return content

    # ── Internal: agent thread ──────────────────────────────────────────────

    def _run_loop(self) -> None:
        """Background thread: owns the Agent and runs process_query()."""
        try:
            while self._running and not self._stop_event.is_set():
                # Check pause
                if not self._pause_event.is_set():
                    self._pause_event.wait(timeout=0.5)
                    continue

                # Wait for a query
                try:
                    query = self._query_queue.get(timeout=0.5)
                except queue.Empty:
                    continue

                # Handle special commands
                if query == "[STOP]":
                    break
                if query == "[RESET]":
                    if self._agent is not None:
                        self._agent.reset()
                    continue

                # Process the query
                self._processing = True
                try:
                    for raw_event in self._agent.process_query(query):
                        if self._stop_event.is_set():
                            break
                        self._map_and_emit(raw_event)

                        # Check pause after each event
                        if not self._pause_event.is_set():
                            break

                        # If the agent yielded a stop_reason, break
                        if raw_event.get("stop_reason"):
                            break
                except Exception as exc:
                    traceback.print_exc()
                    self._emit({
                        "type": "error",
                        "error_type": "PROCESS_QUERY_ERROR",
                        "message": str(exc),
                        "traceback": traceback.format_exc(),
                    })
                finally:
                    self._processing = False
                    self._map_and_emit({
                        "type": "session_stop",
                        "stop_reason": "completed",
                        "is_running": self._get_is_running(),
                    })
                    self._emit({
                        "type": "state_changed",
                        "state": "IDLE",
                        "is_running": self._get_is_running(),
                    })
        except Exception as exc:
            traceback.print_exc()
            self._emit({
                "type": "error",
                "error_type": "BRIDGE_LOOP_ERROR",
                "message": str(exc),
                "traceback": traceback.format_exc(),
            })
        finally:
            self._running = False
            self._emit({
                "type": "state_changed",
                "state": "IDLE",
                "is_running": False,
            })
            self._emit({"type": "thread_finished"})


# ══════════════════════════════════════════════════════════════════════════════
#  Convenience factory
# ══════════════════════════════════════════════════════════════════════════════

def create_bridge(event_callback: Optional[Callable[[Dict[str, Any]], None]] = None) -> WebAgentBridge:
    """Factory function – create a WebAgentBridge with optional callback."""
    return WebAgentBridge(event_callback=event_callback)
